#!/usr/bin/env python3
"""okf deterministic index syncer middleware.

Generates and maintains deterministic index.md files for every directory
under <wiki-root>/wiki/ based on OKF frontmatter metadata (title, description).

Idempotent — uses SHA-256 content hashing to avoid rewriting unchanged files.
Inspired by openwiki's index-middleware.ts.

Usage:
    sync.py <wiki-root> [--dry-run] [--dir <specific-dir>]

Exit codes:
    0 — all indexes synced (or dry-run completed)
    1 — error during sync
"""

import argparse
import json
import os
import re
import stat
import sys
import uuid
from urllib.parse import quote

import yaml

# Files to exclude from listings (hidden from generated indexes). Shared with
# guard.py and validate.py so the three agree on what "generated" means.
from okf_paths import LISTING_SKIP_FILES as SKIP_FILES, in_set
from ownership import (ensure_git_metadata_safe, record_sync,
                       validate_before_sync, verified_entries)


GENERATED_MARKER = '<!-- Generated by OKF middleware; do not edit. -->'


def parse_frontmatter(content):
    """Extract *title* and *description* from an OKF YAML frontmatter block.

    Handles ``---`` delimited blocks. Returns ``(title, description)`` where
    either value may be ``None`` if absent from the frontmatter or if no
    frontmatter block exists.

    YAML parsing preserves folded and multiline values, which are flattened
    only when rendered into a single index entry.
    """
    text = content.lstrip('\ufeff')
    opening = re.match(r'\A---[ \t]*\r?\n', text)
    if opening is None:
        return None, None
    rest = text[opening.end():]
    closing = re.search(r'(?m)^(?:---|\.\.\.)[ \t]*(?:\r?\n|$)', rest)
    if closing is None:
        return None, None
    try:
        data = yaml.safe_load(rest[:closing.start()])
    except yaml.YAMLError:
        return None, None
    if not isinstance(data, dict):
        return None, None
    title = data.get('title')
    description = data.get('description')
    return (title if isinstance(title, str) else None,
            description if isinstance(description, str) else None)


def _md_files(dirpath):
    """Return sorted list of .md filenames for *dirpath*, excluding skips.

    Excludes:
    - Dot-prefixed files (e.g. ``.hidden.md``)
    - Reserved filenames: ``index.md``, ``log.md``, ``_plan.md``,
      ``INSTRUCTIONS.md``
    - Non-.md files entirely.
    """
    files = []
    try:
        for entry in os.scandir(dirpath):
            if entry.name.startswith('.'):
                continue
            if entry.is_symlink() or not entry.is_file() or not entry.name.lower().endswith('.md'):
                continue
            if in_set(entry.name, SKIP_FILES):
                continue
            files.append(entry.name)
    except PermissionError:
        pass
    files.sort()
    return files


def _base_files(dirpath):
    """Return sorted list of ``.base`` filenames (Obsidian Bases views).

    Bases views are directory content worth surfacing for progressive
    disclosure, but they are not OKF concept documents: they carry no ``---``
    frontmatter, so there is no title/description to read and they are listed
    by filename stem. A directory that holds only ``.base`` files (e.g. a
    ``meta/`` folder of dashboards) still gets a generated ``index.md`` so the
    parent directory link never dangles.
    """
    files = []
    try:
        for entry in os.scandir(dirpath):
            if entry.name.startswith('.'):
                continue
            if not entry.is_symlink() and entry.is_file() and entry.name.endswith('.base'):
                files.append(entry.name)
    except PermissionError:
        pass
    files.sort()
    return files


def _subdirs(dirpath):
    """Return sorted list of non-dot-prefixed subdirectory names."""
    dirs = []
    try:
        for entry in os.scandir(dirpath):
            if entry.name.startswith('.'):
                continue
            if not entry.is_symlink() and entry.is_dir():
                dirs.append(entry.name)
    except PermissionError:
        pass
    dirs.sort()
    return dirs


def _md_files_at(directory_fd):
    files = []
    with os.scandir(directory_fd) as entries:
        for entry in entries:
            if (entry.name.startswith('.') or entry.is_symlink() or
                    not entry.is_file(follow_symlinks=False) or
                    not entry.name.lower().endswith('.md') or
                    in_set(entry.name, SKIP_FILES)):
                continue
            files.append(entry.name)
    return sorted(files)


def _base_files_at(directory_fd):
    with os.scandir(directory_fd) as entries:
        return sorted(entry.name for entry in entries
                      if not entry.name.startswith('.') and
                      not entry.is_symlink() and
                      entry.is_file(follow_symlinks=False) and
                      entry.name.endswith('.base'))


def _subdirs_at(directory_fd):
    with os.scandir(directory_fd) as entries:
        return sorted(entry.name for entry in entries
                      if not entry.name.startswith('.') and
                      not entry.is_symlink() and
                      entry.is_dir(follow_symlinks=False))


def _read_page_at(directory_fd, name):
    flags = os.O_RDONLY | getattr(os, 'O_NOFOLLOW', 0)
    fd = os.open(name, flags, dir_fd=directory_fd)
    try:
        if not stat.S_ISREG(os.fstat(fd).st_mode):
            return ''
        chunks = []
        while True:
            chunk = os.read(fd, 65536)
            if not chunk:
                break
            chunks.append(chunk)
        return b''.join(chunks).decode('utf-8', errors='replace')
    finally:
        os.close(fd)


def _index_text(value):
    """Keep untrusted frontmatter on one line and out of link syntax."""
    return (re.sub(r'\s+', ' ', value).strip()
            .replace('\\', '\\\\').replace('[', '\\[').replace(']', '\\]'))


def build_index_content(dirpath, is_root, directory_fd=None):
    """Build the markdown content for an ``index.md`` file.

    Returns the full markdown string, or ``None`` when the directory contains
    no .md files (after exclusions), no .base views, and no subdirectories.
    """
    if directory_fd is None:
        files = _md_files(dirpath)
        bases = _base_files(dirpath)
        subdirs = _subdirs(dirpath)
    else:
        files = _md_files_at(directory_fd)
        bases = _base_files_at(directory_fd)
        subdirs = _subdirs_at(directory_fd)

    if not files and not bases and not subdirs:
        return None

    lines = []

    if is_root:
        lines.append('---')
        lines.append('okf_version: "0.2"')
        lines.append('---')
        lines.append('')

    # Each present content type is one section. Emitting a section header only
    # when it has entries keeps a base-only directory (empty ``# Files``) clean;
    # a directory with .md files renders byte-identically to before.
    sections = []

    if files:
        section = ['# Files', '']
        for fname in files:
            title = None
            desc = None
            try:
                if directory_fd is None:
                    with open(os.path.join(dirpath, fname), 'r',
                              encoding='utf-8', errors='replace') as fh:
                        page_content = fh.read()
                else:
                    page_content = _read_page_at(directory_fd, fname)
                title, desc = parse_frontmatter(page_content)
            except (OSError, IOError):
                pass

            if not title:
                title = os.path.splitext(fname)[0]

            href = quote(fname, safe='')
            if desc:
                section.append(f'- [{_index_text(title)}]({href}) - {_index_text(desc)}')
            else:
                section.append(f'- [{_index_text(title)}]({href})')
        sections.append(section)

    if bases:
        section = ['# Bases', '']
        for bname in bases:
            href = quote(bname, safe='')
            title = os.path.splitext(bname)[0]
            section.append(f'- [{_index_text(title)}]({href})')
        sections.append(section)

    if subdirs:
        section = ['# Directories', '']
        for dname in subdirs:
            href = quote(dname, safe='') + '/'
            section.append(f'- [{_index_text(dname)}/]({href})')
        sections.append(section)

    for section in sections:
        lines.extend(section)
        lines.append('')

    if is_root:
        lines.insert(4, GENERATED_MARKER)
    else:
        lines.insert(0, GENERATED_MARKER)
    return '\n'.join(lines)


def _same_file(left, right):
    return left.st_dev == right.st_dev and left.st_ino == right.st_ino


def _read_index_at(directory_fd, name='index.md'):
    try:
        before = os.stat(name, dir_fd=directory_fd,
                         follow_symlinks=False)
    except FileNotFoundError:
        raise
    if not stat.S_ISREG(before.st_mode):
        raise OSError('existing index.md is not a regular file')
    flags = os.O_RDONLY | getattr(os, 'O_NOFOLLOW', 0)
    fd = os.open(name, flags, dir_fd=directory_fd)
    try:
        opened = os.fstat(fd)
        if not stat.S_ISREG(opened.st_mode) or not _same_file(before, opened):
            raise OSError('index.md changed while being inspected')
        chunks = []
        while True:
            chunk = os.read(fd, 65536)
            if not chunk:
                break
            chunks.append(chunk)
        return opened, b''.join(chunks)
    finally:
        os.close(fd)


def _unlink_index_at(directory_fd, expected, expected_content):
    quarantine = f'.index.md.{uuid.uuid4().hex}.remove'
    os.rename('index.md', quarantine, src_dir_fd=directory_fd,
              dst_dir_fd=directory_fd)
    try:
        current, content = _read_index_at(directory_fd, quarantine)
        marker = (GENERATED_MARKER + '\n').encode('utf-8')
        if (_same_file(expected, current) and content == expected_content and
                marker in content):
            os.unlink(quarantine, dir_fd=directory_fd)
            return
        # Restore only if the public name is still vacant. Otherwise leave the
        # quarantined bytes intact rather than overwrite a concurrent file.
        os.link(quarantine, 'index.md', src_dir_fd=directory_fd,
                dst_dir_fd=directory_fd, follow_symlinks=False)
        os.unlink(quarantine, dir_fd=directory_fd)
        raise OSError('index.md changed before generated index removal')
    except OSError as exc:
        if isinstance(exc, FileNotFoundError):
            raise OSError('index.md changed before generated index removal') from exc
        try:
            os.link(quarantine, 'index.md', src_dir_fd=directory_fd,
                    dst_dir_fd=directory_fd, follow_symlinks=False)
            os.unlink(quarantine, dir_fd=directory_fd)
        except OSError:
            # Keep the quarantined entry if it cannot be safely restored.
            raise OSError(
                f'index.md changed before generated index removal; recover prior index at {quarantine}'
            ) from exc
        raise OSError('index.md changed before generated index removal') from exc


def _restore_quarantine_at(directory_fd, quarantine):
    try:
        os.link(quarantine, 'index.md', src_dir_fd=directory_fd,
                dst_dir_fd=directory_fd, follow_symlinks=False)
        os.unlink(quarantine, dir_fd=directory_fd)
        return None
    except OSError:
        return quarantine


def _replace_index_at(directory_fd, content, expected, expected_content):
    temp_name = f'.index.md.{uuid.uuid4().hex}.tmp'
    flags = (os.O_WRONLY | os.O_CREAT | os.O_EXCL |
             getattr(os, 'O_NOFOLLOW', 0))
    fd = os.open(temp_name, flags, 0o666, dir_fd=directory_fd)
    try:
        view = memoryview(content)
        while view:
            written = os.write(fd, view)
            view = view[written:]
    finally:
        os.close(fd)

    try:
        try:
            current, current_content = _read_index_at(directory_fd)
        except FileNotFoundError:
            current, current_content = None, None
        if expected is None:
            if current is not None:
                raise OSError('index.md appeared before generated index write')
            # link() installs atomically only if no entry already exists.
            os.link(temp_name, 'index.md', src_dir_fd=directory_fd,
                    dst_dir_fd=directory_fd, follow_symlinks=False)
            os.unlink(temp_name, dir_fd=directory_fd)
            return

        marker = (GENERATED_MARKER + '\n').encode('utf-8')
        if (current is None or not _same_file(expected, current) or
                current_content != expected_content or marker not in current_content):
            raise OSError('index.md changed before generated index update')

        quarantine = f'.index.md.{uuid.uuid4().hex}.recovery'
        os.rename('index.md', quarantine, src_dir_fd=directory_fd,
                  dst_dir_fd=directory_fd)
        try:
            moved_stat, moved_content = _read_index_at(directory_fd, quarantine)
        except OSError as exc:
            recovery = _restore_quarantine_at(directory_fd, quarantine)
            suffix = f'; recover previous index at {recovery}' if recovery else ''
            raise OSError('could not verify quarantined index' + suffix) from exc
        if (not _same_file(expected, moved_stat) or
                moved_content != current_content or marker not in moved_content):
            recovery = _restore_quarantine_at(directory_fd, quarantine)
            suffix = f'; recover previous index at {recovery}' if recovery else ''
            raise OSError('index.md changed during generated index update' + suffix)
        try:
            os.link(temp_name, 'index.md', src_dir_fd=directory_fd,
                    dst_dir_fd=directory_fd, follow_symlinks=False)
        except OSError as exc:
            recovery = _restore_quarantine_at(directory_fd, quarantine)
            suffix = f'; recover previous index at {recovery}' if recovery else ''
            raise OSError('index.md arrival prevented generated index update' + suffix) from exc
        os.unlink(quarantine, dir_fd=directory_fd)
    finally:
        try:
            os.unlink(temp_name, dir_fd=directory_fd)
        except FileNotFoundError:
            pass


def _open_directory_at(wiki_dir, dirpath):
    flags = (os.O_RDONLY | getattr(os, 'O_DIRECTORY', 0) |
             getattr(os, 'O_NOFOLLOW', 0))
    fd = os.open(wiki_dir, flags)
    try:
        for part in filter(None, dirpath.split(os.sep)):
            child = os.open(part, flags, dir_fd=fd)
            os.close(fd)
            fd = child
        return fd
    except BaseException:
        os.close(fd)
        raise


def _sync_directory_pinned(wiki_dir, dirpath, dry_run, directory_fd):
    """Sync a single directory under *wiki_dir*.

    Parameters
    ----------
    wiki_dir:
        Absolute path to ``<root>/wiki/``.
    dirpath:
        Relative path from *wiki_dir* (``''`` for the wiki root).
    dry_run:
        When ``True``, print what would happen without writing.

    Returns
    -------
    ``(status, rel, detail)`` where *status* is ``'OK'`` | ``'WRITE'`` |
    ``'SKIP'`` | ``'DRY-RUN'``, *rel* is a human-readable relative path,
    and *detail* is a short description.
    """
    full_path = os.path.join(wiki_dir, dirpath) if dirpath else wiki_dir
    is_root = (dirpath == '')

    def public_path_is_pinned():
        try:
            public = os.stat(full_path, follow_symlinks=False)
            pinned = os.fstat(directory_fd)
            return (stat.S_ISDIR(public.st_mode) and
                    public.st_dev == pinned.st_dev and public.st_ino == pinned.st_ino)
        except OSError:
            return False

    if not public_path_is_pinned():
        return ('ERROR', os.path.join('wiki', dirpath) if dirpath else 'wiki',
                'directory path changed during sync')

    content = build_index_content(full_path, is_root, directory_fd)

    rel = os.path.join('wiki', dirpath) if dirpath else 'wiki'
    index_path = os.path.join(full_path, 'index.md')
    if content is None:
        try:
            index_stat, existing = _read_index_at(directory_fd)
        except FileNotFoundError:
            return ('SKIP', rel + '/', 'no content')
        except OSError as exc:
            return ('ERROR', rel + '/index.md', str(exc))
        marker = (GENERATED_MARKER + '\n').encode('utf-8')
        if marker not in existing:
            return ('ERROR', rel + '/index.md',
                    'unmarked index in empty directory requires manual review')
        try:
            before_hash, baseline_clean = validate_before_sync(
                os.path.dirname(wiki_dir), rel + '/index.md', existing)
        except OSError as exc:
            return ('ERROR', rel + '/index.md', str(exc))
        if dry_run:
            if not public_path_is_pinned():
                return ('ERROR', rel + '/index.md', 'directory path changed during sync')
            return ('DRY-RUN', rel + '/index.md', 'would remove empty generated index')
        if not public_path_is_pinned():
            return ('ERROR', rel + '/index.md', 'directory path changed during sync')
        try:
            _unlink_index_at(directory_fd, index_stat, existing)
            record_sync(os.path.dirname(wiki_dir), rel + '/index.md', before_hash, None,
                        baseline_clean=baseline_clean)
        except OSError as exc:
            return ('ERROR', rel + '/index.md', str(exc))
        if not public_path_is_pinned():
            return ('ERROR', rel + '/index.md', 'directory path changed during sync')
        return ('WRITE', rel + '/index.md', 'removed empty generated index')

    try:
        index_stat, existing = _read_index_at(directory_fd)
    except FileNotFoundError:
        index_stat, existing = None, None
    except OSError as exc:
        return ('ERROR', rel + '/index.md', str(exc))

    if index_stat is not None:
        generated = content.encode('utf-8')
        marker = (GENERATED_MARKER + '\n').encode('utf-8')
        unmarked_generated = generated.replace(marker, b'', 1)
        if existing in (generated, unmarked_generated):
            if not public_path_is_pinned():
                return ('ERROR', rel + '/index.md', 'directory path changed during sync')
            return ('OK', rel + '/index.md', 'unchanged')
        if marker not in existing:
            return ('ERROR', rel + '/index.md',
                    'unmarked index differs from generated content; review and '
                    'migrate it manually before syncing')

    try:
        before_hash, baseline_clean = validate_before_sync(
            os.path.dirname(wiki_dir), rel + '/index.md', existing)
    except OSError as exc:
        return ('ERROR', rel + '/index.md', str(exc))

    if dry_run:
        file_count = len(_md_files(full_path))
        base_count = len(_base_files(full_path))
        dir_count = len(_subdirs(full_path))
        return ('DRY-RUN', rel + '/index.md',
                f'{file_count} files, {base_count} bases, '
                f'{dir_count} directories')

    if not public_path_is_pinned():
        return ('ERROR', rel + '/index.md', 'directory path changed during sync')
    try:
        _replace_index_at(directory_fd, content.encode('utf-8'), index_stat,
                          existing)
        if not public_path_is_pinned():
            return ('ERROR', rel + '/index.md', 'directory path changed during sync')
        record_sync(os.path.dirname(wiki_dir), rel + '/index.md', before_hash,
                    content.encode('utf-8'), baseline_clean=baseline_clean)
    except OSError as exc:
        return ('ERROR', rel + '/index.md', str(exc))

    file_count = len(_md_files(full_path))
    base_count = len(_base_files(full_path))
    dir_count = len(_subdirs(full_path))
    return ('WRITE', rel + '/index.md',
            f'{file_count} files, {base_count} bases, '
            f'{dir_count} directories')


def sync_directory(wiki_dir, dirpath, dry_run=False):
    """Sync a directory while pinning each path component without following symlinks."""
    try:
        directory_fd = _open_directory_at(wiki_dir, dirpath)
    except OSError as exc:
        rel = os.path.join('wiki', dirpath) if dirpath else 'wiki'
        return ('ERROR', rel, str(exc))
    try:
        return _sync_directory_pinned(wiki_dir, dirpath, dry_run, directory_fd)
    finally:
        os.close(directory_fd)


def main():
    parser = argparse.ArgumentParser(
        description='Deterministic index.md syncer for OKF wiki vaults')
    parser.add_argument('wiki_root',
                        help='Path to the wiki vault root directory')
    parser.add_argument('--dry-run', action='store_true',
                        help='Print what would be written without writing')
    parser.add_argument('--dir', default=None,
                        help='Only sync this specific directory under wiki/ '
                             '(non-recursive)')
    parser.add_argument('--json', action='store_true',
                        help='Print structured sync results and verified ownership changes')

    args = parser.parse_args()

    wiki_root = os.path.abspath(args.wiki_root)
    wiki_dir = os.path.join(wiki_root, 'wiki')

    if not os.path.isdir(wiki_dir) or os.path.islink(wiki_dir):
        print(f'error: {wiki_dir} does not exist or is not a directory',
              file=sys.stderr)
        sys.exit(1)

    try:
        ensure_git_metadata_safe(wiki_root)
    except OSError as exc:
        if args.json:
            print(json.dumps({'results': [{
                'status': 'ERROR', 'path': '.vault-meta', 'detail': str(exc)
            }], 'changes': []}, sort_keys=True))
        else:
            print(f'[ERROR] .vault-meta ({exc})')
        sys.exit(1)

    results = []
    if args.dir:
        # Sync a single directory (non-recursive)
        target_raw = args.dir.strip('/')
        target = os.path.join(wiki_dir, target_raw)
        parts = target_raw.split('/')
        if (os.path.isabs(args.dir) or '..' in parts or
                not os.path.realpath(target).startswith(os.path.realpath(wiki_dir) + os.sep) or
                any(os.path.islink(os.path.join(wiki_dir, *parts[:i]))
                    for i in range(1, len(parts) + 1)) or
                not os.path.isdir(target)):
            print(f'error: directory not found — wiki/{target_raw}',
                  file=sys.stderr)
            sys.exit(1)
        status, rel, detail = sync_directory(
            wiki_dir, target_raw, dry_run=args.dry_run)
        results.append((status, rel, detail))
    else:
        # Walk the entire wiki tree
        for root, dirnames, _ in os.walk(wiki_dir):
            # Prune hidden directories during traversal
            dirnames[:] = [d for d in dirnames
                           if not d.startswith('.') and
                           not os.path.islink(os.path.join(root, d))]

            rel_dir = os.path.relpath(root, wiki_dir)
            dirpath = '' if rel_dir == '.' else rel_dir

            status, rel, detail = sync_directory(
                wiki_dir, dirpath, dry_run=args.dry_run)
            results.append((status, rel, detail))

    if args.json:
        changed_paths = [rel if rel.endswith('/index.md') else rel + '/index.md'
                         for status, rel, _ in results if status == 'WRITE']
        changes = verified_entries(wiki_root, changed_paths)
        print(json.dumps({'results': [
            {'status': status, 'path': rel, 'detail': detail}
            for status, rel, detail in results
        ], 'changes': changes}, sort_keys=True))
    else:
        for status, rel, detail in results:
            print(f'[{status}] {rel} ({detail})')

    sys.exit(1 if any(status == 'ERROR' for status, _, _ in results) else 0)


if __name__ == '__main__':
    main()
