#!/usr/bin/env python3
"""okf deterministic index syncer middleware.

Generates and maintains deterministic index.md files for every directory
under <wiki-root>/wiki/ based on OKF frontmatter metadata (title, description).

Idempotent — uses SHA-256 content hashing to avoid rewriting unchanged files.
Inspired by openwiki's index-middleware.ts.

Usage:
    sync.py <wiki-root> [--dry-run] [--dir <specific-dir>]

Exit codes:
    0 — all indexes synced (or dry-run completed)
    1 — error during sync
"""

import argparse
import os
import re
import stat
import sys
import uuid
from urllib.parse import quote

import yaml

# Files to exclude from listings (hidden from generated indexes). Shared with
# guard.py and validate.py so the three agree on what "generated" means.
from okf_paths import LISTING_SKIP_FILES as SKIP_FILES, in_set


GENERATED_MARKER = '<!-- Generated by OKF middleware; do not edit. -->'


def parse_frontmatter(content):
    """Extract *title* and *description* from an OKF YAML frontmatter block.

    Handles ``---`` delimited blocks. Returns ``(title, description)`` where
    either value may be ``None`` if absent from the frontmatter or if no
    frontmatter block exists.

    YAML parsing preserves folded and multiline values, which are flattened
    only when rendered into a single index entry.
    """
    text = content.lstrip('\ufeff')
    opening = re.match(r'\A---[ \t]*\r?\n', text)
    if opening is None:
        return None, None
    rest = text[opening.end():]
    closing = re.search(r'(?m)^(?:---|\.\.\.)[ \t]*(?:\r?\n|$)', rest)
    if closing is None:
        return None, None
    try:
        data = yaml.safe_load(rest[:closing.start()])
    except yaml.YAMLError:
        return None, None
    if not isinstance(data, dict):
        return None, None
    title = data.get('title')
    description = data.get('description')
    return (title if isinstance(title, str) else None,
            description if isinstance(description, str) else None)


def _md_files(dirpath):
    """Return sorted list of .md filenames for *dirpath*, excluding skips.

    Excludes:
    - Dot-prefixed files (e.g. ``.hidden.md``)
    - Reserved filenames: ``index.md``, ``log.md``, ``_plan.md``,
      ``INSTRUCTIONS.md``
    - Non-.md files entirely.
    """
    files = []
    try:
        for entry in os.scandir(dirpath):
            if entry.name.startswith('.'):
                continue
            if entry.is_symlink() or not entry.is_file() or not entry.name.endswith('.md'):
                continue
            if in_set(entry.name, SKIP_FILES):
                continue
            files.append(entry.name)
    except PermissionError:
        pass
    files.sort()
    return files


def _base_files(dirpath):
    """Return sorted list of ``.base`` filenames (Obsidian Bases views).

    Bases views are directory content worth surfacing for progressive
    disclosure, but they are not OKF concept documents: they carry no ``---``
    frontmatter, so there is no title/description to read and they are listed
    by filename stem. A directory that holds only ``.base`` files (e.g. a
    ``meta/`` folder of dashboards) still gets a generated ``index.md`` so the
    parent directory link never dangles.
    """
    files = []
    try:
        for entry in os.scandir(dirpath):
            if entry.name.startswith('.'):
                continue
            if not entry.is_symlink() and entry.is_file() and entry.name.endswith('.base'):
                files.append(entry.name)
    except PermissionError:
        pass
    files.sort()
    return files


def _subdirs(dirpath):
    """Return sorted list of non-dot-prefixed subdirectory names."""
    dirs = []
    try:
        for entry in os.scandir(dirpath):
            if entry.name.startswith('.'):
                continue
            if not entry.is_symlink() and entry.is_dir():
                dirs.append(entry.name)
    except PermissionError:
        pass
    dirs.sort()
    return dirs


def _index_text(value):
    """Keep untrusted frontmatter on one line and out of link syntax."""
    return (re.sub(r'\s+', ' ', value).strip()
            .replace('\\', '\\\\').replace('[', '\\[').replace(']', '\\]'))


def build_index_content(dirpath, is_root):
    """Build the markdown content for an ``index.md`` file.

    Returns the full markdown string, or ``None`` when the directory contains
    no .md files (after exclusions), no .base views, and no subdirectories.
    """
    files = _md_files(dirpath)
    bases = _base_files(dirpath)
    subdirs = _subdirs(dirpath)

    if not files and not bases and not subdirs:
        return None

    lines = []

    if is_root:
        lines.append('---')
        lines.append('okf_version: "0.2"')
        lines.append('---')
        lines.append('')

    # Each present content type is one section. Emitting a section header only
    # when it has entries keeps a base-only directory (empty ``# Files``) clean;
    # a directory with .md files renders byte-identically to before.
    sections = []

    if files:
        section = ['# Files', '']
        for fname in files:
            fpath = os.path.join(dirpath, fname)
            title = None
            desc = None
            try:
                with open(fpath, 'r', encoding='utf-8', errors='replace') as fh:
                    content = fh.read()
                title, desc = parse_frontmatter(content)
            except (OSError, IOError):
                pass

            if not title:
                title = os.path.splitext(fname)[0]

            href = quote(fname, safe='')
            if desc:
                section.append(f'- [{_index_text(title)}]({href}) - {_index_text(desc)}')
            else:
                section.append(f'- [{_index_text(title)}]({href})')
        sections.append(section)

    if bases:
        section = ['# Bases', '']
        for bname in bases:
            href = quote(bname, safe='')
            title = os.path.splitext(bname)[0]
            section.append(f'- [{title}]({href})')
        sections.append(section)

    if subdirs:
        section = ['# Directories', '']
        for dname in subdirs:
            href = quote(dname, safe='') + '/'
            section.append(f'- [{dname}/]({href})')
        sections.append(section)

    for section in sections:
        lines.extend(section)
        lines.append('')

    if is_root:
        lines.insert(4, GENERATED_MARKER)
    else:
        lines.insert(0, GENERATED_MARKER)
    return '\n'.join(lines)


def _same_file(left, right):
    return left.st_dev == right.st_dev and left.st_ino == right.st_ino


def _read_index_at(directory_fd, name='index.md'):
    try:
        before = os.stat(name, dir_fd=directory_fd,
                         follow_symlinks=False)
    except FileNotFoundError:
        raise
    if not stat.S_ISREG(before.st_mode):
        raise OSError('existing index.md is not a regular file')
    flags = os.O_RDONLY | getattr(os, 'O_NOFOLLOW', 0)
    fd = os.open(name, flags, dir_fd=directory_fd)
    try:
        opened = os.fstat(fd)
        if not stat.S_ISREG(opened.st_mode) or not _same_file(before, opened):
            raise OSError('index.md changed while being inspected')
        chunks = []
        while True:
            chunk = os.read(fd, 65536)
            if not chunk:
                break
            chunks.append(chunk)
        return opened, b''.join(chunks)
    finally:
        os.close(fd)


def _unlink_index_at(directory_fd, expected):
    quarantine = f'.index.md.{uuid.uuid4().hex}.remove'
    os.rename('index.md', quarantine, src_dir_fd=directory_fd,
              dst_dir_fd=directory_fd)
    try:
        current, content = _read_index_at(directory_fd, quarantine)
        marker = (GENERATED_MARKER + '\n').encode('utf-8')
        if _same_file(expected, current) and marker in content:
            os.unlink(quarantine, dir_fd=directory_fd)
            return
        # Restore only if the public name is still vacant. Otherwise leave the
        # quarantined bytes intact rather than overwrite a concurrent file.
        os.link(quarantine, 'index.md', src_dir_fd=directory_fd,
                dst_dir_fd=directory_fd, follow_symlinks=False)
        os.unlink(quarantine, dir_fd=directory_fd)
        raise OSError('index.md changed before generated index removal')
    except OSError as exc:
        if isinstance(exc, FileNotFoundError):
            raise OSError('index.md changed before generated index removal') from exc
        try:
            os.link(quarantine, 'index.md', src_dir_fd=directory_fd,
                    dst_dir_fd=directory_fd, follow_symlinks=False)
            os.unlink(quarantine, dir_fd=directory_fd)
        except OSError:
            # Keep the quarantined entry if it cannot be safely restored.
            pass
        raise OSError('index.md changed before generated index removal') from exc


def _replace_index_at(directory_fd, content, expected):
    temp_name = f'.index.md.{uuid.uuid4().hex}.tmp'
    flags = (os.O_WRONLY | os.O_CREAT | os.O_EXCL |
             getattr(os, 'O_NOFOLLOW', 0))
    fd = os.open(temp_name, flags, 0o666, dir_fd=directory_fd)
    try:
        view = memoryview(content)
        while view:
            written = os.write(fd, view)
            view = view[written:]
    finally:
        os.close(fd)

    try:
        try:
            current, current_content = _read_index_at(directory_fd)
        except FileNotFoundError:
            current, current_content = None, None
        if expected is None:
            if current is not None:
                raise OSError('index.md appeared before generated index write')
            # link() installs atomically only if no entry already exists.
            os.link(temp_name, 'index.md', src_dir_fd=directory_fd,
                    dst_dir_fd=directory_fd, follow_symlinks=False)
            os.unlink(temp_name, dir_fd=directory_fd)
            return

        marker = (GENERATED_MARKER + '\n').encode('utf-8')
        if (current is None or not _same_file(expected, current) or
                marker not in current_content):
            raise OSError('index.md changed before generated index update')
        os.replace(temp_name, 'index.md', src_dir_fd=directory_fd,
                   dst_dir_fd=directory_fd)
    finally:
        try:
            os.unlink(temp_name, dir_fd=directory_fd)
        except FileNotFoundError:
            pass


def _open_directory_at(wiki_dir, dirpath):
    flags = (os.O_RDONLY | getattr(os, 'O_DIRECTORY', 0) |
             getattr(os, 'O_NOFOLLOW', 0))
    fd = os.open(wiki_dir, flags)
    try:
        for part in filter(None, dirpath.split(os.sep)):
            child = os.open(part, flags, dir_fd=fd)
            os.close(fd)
            fd = child
        return fd
    except BaseException:
        os.close(fd)
        raise


def _sync_directory_pinned(wiki_dir, dirpath, dry_run, directory_fd):
    """Sync a single directory under *wiki_dir*.

    Parameters
    ----------
    wiki_dir:
        Absolute path to ``<root>/wiki/``.
    dirpath:
        Relative path from *wiki_dir* (``''`` for the wiki root).
    dry_run:
        When ``True``, print what would happen without writing.

    Returns
    -------
    ``(status, rel, detail)`` where *status* is ``'OK'`` | ``'WRITE'`` |
    ``'SKIP'`` | ``'DRY-RUN'``, *rel* is a human-readable relative path,
    and *detail* is a short description.
    """
    full_path = os.path.join(wiki_dir, dirpath) if dirpath else wiki_dir
    is_root = (dirpath == '')

    if not os.path.isdir(full_path):
        return ('SKIP', os.path.join('wiki', dirpath) if dirpath else 'wiki',
                'not a directory')

    content = build_index_content(full_path, is_root)

    rel = os.path.join('wiki', dirpath) if dirpath else 'wiki'
    index_path = os.path.join(full_path, 'index.md')
    if content is None:
        try:
            index_stat, existing = _read_index_at(directory_fd)
        except FileNotFoundError:
            return ('SKIP', rel + '/', 'no content')
        except OSError as exc:
            return ('ERROR', rel + '/index.md', str(exc))
        marker = (GENERATED_MARKER + '\n').encode('utf-8')
        if marker not in existing:
            return ('ERROR', rel + '/index.md',
                    'unmarked index in empty directory requires manual review')
        if dry_run:
            return ('DRY-RUN', rel + '/index.md', 'would remove empty generated index')
        try:
            _unlink_index_at(directory_fd, index_stat)
        except OSError as exc:
            return ('ERROR', rel + '/index.md', str(exc))
        return ('WRITE', rel + '/index.md', 'removed empty generated index')

    try:
        index_stat, existing = _read_index_at(directory_fd)
    except FileNotFoundError:
        index_stat, existing = None, None
    except OSError as exc:
        return ('ERROR', rel + '/index.md', str(exc))

    if index_stat is not None:
        generated = content.encode('utf-8')
        marker = (GENERATED_MARKER + '\n').encode('utf-8')
        unmarked_generated = generated.replace(marker, b'', 1)
        if existing in (generated, unmarked_generated):
            return ('OK', rel + '/index.md', 'unchanged')
        if marker not in existing:
            return ('ERROR', rel + '/index.md',
                    'unmarked index differs from generated content; review and '
                    'migrate it manually before syncing')

    if dry_run:
        file_count = len(_md_files(full_path))
        base_count = len(_base_files(full_path))
        dir_count = len(_subdirs(full_path))
        return ('DRY-RUN', rel + '/index.md',
                f'{file_count} files, {base_count} bases, '
                f'{dir_count} directories')

    try:
        _replace_index_at(directory_fd, content.encode('utf-8'), index_stat)
    except OSError as exc:
        return ('ERROR', rel + '/index.md', str(exc))

    file_count = len(_md_files(full_path))
    base_count = len(_base_files(full_path))
    dir_count = len(_subdirs(full_path))
    return ('WRITE', rel + '/index.md',
            f'{file_count} files, {base_count} bases, '
            f'{dir_count} directories')


def sync_directory(wiki_dir, dirpath, dry_run=False):
    """Sync a directory while pinning each path component without following symlinks."""
    try:
        directory_fd = _open_directory_at(wiki_dir, dirpath)
    except OSError as exc:
        rel = os.path.join('wiki', dirpath) if dirpath else 'wiki'
        return ('ERROR', rel, str(exc))
    try:
        return _sync_directory_pinned(wiki_dir, dirpath, dry_run, directory_fd)
    finally:
        os.close(directory_fd)


def main():
    parser = argparse.ArgumentParser(
        description='Deterministic index.md syncer for OKF wiki vaults')
    parser.add_argument('wiki_root',
                        help='Path to the wiki vault root directory')
    parser.add_argument('--dry-run', action='store_true',
                        help='Print what would be written without writing')
    parser.add_argument('--dir', default=None,
                        help='Only sync this specific directory under wiki/ '
                             '(non-recursive)')

    args = parser.parse_args()

    wiki_root = os.path.abspath(args.wiki_root)
    wiki_dir = os.path.join(wiki_root, 'wiki')

    if not os.path.isdir(wiki_dir) or os.path.islink(wiki_dir):
        print(f'error: {wiki_dir} does not exist or is not a directory',
              file=sys.stderr)
        sys.exit(1)

    results = []
    if args.dir:
        # Sync a single directory (non-recursive)
        target_raw = args.dir.strip('/')
        target = os.path.join(wiki_dir, target_raw)
        parts = target_raw.split('/')
        if (os.path.isabs(args.dir) or '..' in parts or
                not os.path.realpath(target).startswith(os.path.realpath(wiki_dir) + os.sep) or
                any(os.path.islink(os.path.join(wiki_dir, *parts[:i]))
                    for i in range(1, len(parts) + 1)) or
                not os.path.isdir(target)):
            print(f'error: directory not found — wiki/{target_raw}',
                  file=sys.stderr)
            sys.exit(1)
        status, rel, detail = sync_directory(
            wiki_dir, target_raw, dry_run=args.dry_run)
        print(f'[{status}] {rel} ({detail})')
        results.append((status, rel, detail))
    else:
        # Walk the entire wiki tree
        for root, dirnames, _ in os.walk(wiki_dir):
            # Prune hidden directories during traversal
            dirnames[:] = [d for d in dirnames
                           if not d.startswith('.') and
                           not os.path.islink(os.path.join(root, d))]

            rel_dir = os.path.relpath(root, wiki_dir)
            dirpath = '' if rel_dir == '.' else rel_dir

            status, rel, detail = sync_directory(
                wiki_dir, dirpath, dry_run=args.dry_run)
            results.append((status, rel, detail))

        for status, rel, detail in results:
            print(f'[{status}] {rel} ({detail})')

    sys.exit(1 if any(status == 'ERROR' for status, _, _ in results) else 0)


if __name__ == '__main__':
    main()
