#!/usr/bin/env python3
"""Boundary and content regressions for the wiki Python middleware."""

import builtins
import json
from pathlib import Path
import subprocess
import sys
import tempfile
from unittest.mock import patch

middleware = Path(sys.argv[1]).resolve()


def run(script: Path, *args: str, ok: bool = True) -> subprocess.CompletedProcess:
    result = subprocess.run(
        [sys.executable, str(script), *map(str, args)],
        text=True, capture_output=True, check=False,
    )
    if ok and result.returncode:
        raise AssertionError(f"{script.name} unexpectedly failed: {result.stderr}")
    if not ok and result.returncode == 0:
        raise AssertionError(f"{script.name} unexpectedly succeeded: {args}")
    return result


with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    wiki = root / "wiki"
    topic = wiki / "topic"
    outside = root / "outside"
    topic.mkdir(parents=True)
    outside.mkdir()
    (wiki / ".raw").mkdir()
    page = topic / "page.md"
    page.write_text('---\ntype: note\ntitle: "A [link]"\n'
                    'description: >\n  first line\n  second line\n---\n[[dest]]\n')
    (wiki / "dest.md").write_text("---\ntype: note\ntitle: Dest\n---\n")
    foreign = outside / "foreign.md"
    foreign.write_text("---\ntype: note\n---\n[[dest]]\n")
    (wiki / "alias").symlink_to(outside, target_is_directory=True)
    (wiki / "foreign.md").symlink_to(foreign)

    guard = middleware / "guard.py"
    run(guard, root, "wiki/topic/page.md")
    run(guard, root, "wiki/_plan.md")
    run(guard, "--if-wiki", root, "outside/other.md")
    for blocked in ("wiki/index.md", "wiki/topic/index.md", "wiki/log.md",
                    "wiki/topic/log.md", "wiki/.raw/secret.env",
                    "wiki/alias/new.md", "wiki/foreign.md", "wiki/../outside/foreign.md"):
        run(guard, root, blocked, ok=False)
    # An absolute path that uses macOS's /var alias must still be recognized.
    run(guard, "--if-wiki", root, page)

    validator = middleware / "validate.py"
    run(validator, page)
    invalid = wiki / "invalid.md"
    invalid.write_text("---\ntype: note\n---not-a-delimiter\n")
    run(validator, invalid, ok=False)
    invalid.unlink()

    sync = middleware / "sync.py"
    for directory in ("../outside", "alias"):
        run(sync, root, "--dir", directory, ok=False)
    assert not (outside / "index.md").exists()
    run(sync, root)
    index = (wiki / "index.md").read_text()
    assert "[alias/]" not in index and "[foreign]" not in index
    assert "[A \\[link\\]](page.md) - first line second line" in (topic / "index.md").read_text()
    assert "<!-- Generated by OKF middleware; do not edit. -->" in index
    assert "<!-- Generated by OKF middleware; do not edit. -->" in (topic / "index.md").read_text()
    assert "[topic/](topic/)" in index
    lint = json.loads(run(middleware / "lint.py", root).stdout)
    assert not lint["stale_index_entries"] and not lint["dead_links"]


with tempfile.TemporaryDirectory() as temp:
    sys.path.insert(0, str(middleware))
    import sync as sync_module

    root = Path(temp) / "vault"
    wiki = root / "wiki"
    nested = wiki / "nested"
    nested.mkdir(parents=True)
    page = nested / "page.md"
    page.write_text("---\ntype: note\n---\n")
    outside = root / "outside.md"
    outside.write_text("user data must survive\\n")
    (nested / "index.md").symlink_to(outside)

    sync = middleware / "sync.py"
    result = run(sync, root, "--dry-run", ok=False)
    assert outside.read_text() == "user data must survive\\n"
    assert "[ERROR]" in result.stdout
    result = run(sync, root, ok=False)
    assert outside.read_text() == "user data must survive\\n"
    assert "[ERROR]" in result.stdout

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    nested = root / "wiki" / "nested"
    nested.mkdir(parents=True)
    (nested / "page.md").write_text("---\ntype: note\n---\n")
    (nested / "index.md").mkdir()

    sync = middleware / "sync.py"
    result = run(sync, root, "--dir", "nested", ok=False)
    assert "[ERROR]" in result.stdout
    result = run(sync, root, ok=False)
    assert "[ERROR]" in result.stdout

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    nested = root / "wiki" / "nested"
    nested.mkdir(parents=True)
    (nested / "page.md").write_text("---\\ntype: note\\n---\\n")
    index = nested / "index.md"
    original = "Handwritten content\\n"
    index.write_text(original)
    sync = middleware / "sync.py"
    result = run(sync, root, "--dir", "nested", ok=False)
    assert "unmarked index differs" in result.stdout
    assert index.read_text() == original
    result = run(sync, root, ok=False)
    assert "unmarked index differs" in result.stdout
    assert index.read_text() == original

    index.unlink()
    run(sync, root, "--dir", "nested")
    assert "<!-- Generated by OKF middleware; do not edit. -->" in index.read_text()
    (nested / "another.md").write_text("---\\ntype: note\\n---\\n")
    run(sync, root, "--dir", "nested")
    generated = index.read_text()
    assert "(another.md)" in generated
    index.write_text(generated.replace(
        "<!-- Generated by OKF middleware; do not edit. -->\n", "", 1))
    legacy_bytes = index.read_bytes()
    run(sync, root, "--dir", "nested")
    assert index.read_bytes() == legacy_bytes

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    empty = root / "wiki" / "empty"
    empty.mkdir(parents=True)
    index = empty / "index.md"
    index.write_text("handwritten index\\n")
    result = run(middleware / "sync.py", root, ok=False)
    assert "unmarked index" in result.stdout
    assert index.read_text() == "handwritten index\\n"

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    empty = root / "wiki" / "topic"
    empty.mkdir(parents=True)
    page = empty / "page.md"
    page.write_text("---\\ntype: note\\n---\\n")
    sync = middleware / "sync.py"
    run(sync, root, "--dir", "topic")
    index = empty / "index.md"
    assert index.exists()
    page.unlink()
    run(sync, root, "--dir", "topic", "--dry-run")
    assert index.exists()
    run(sync, root, "--dir", "topic")
    assert not index.exists()

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    wiki = root / "wiki"
    nested = wiki / "nested"
    nested.mkdir(parents=True)
    (nested / "page.md").write_text("---\ntype: note\n---\n")
    index = nested / "index.md"
    outside = root / "outside.md"
    outside.write_text("outside sentinel\n")
    index.write_text("<!-- Generated by OKF middleware; do not edit. -->\nold index\n")
    real_open = builtins.open

    def swap_for_symlink(file, mode="r", *args, **kwargs):
        if Path(file) == index and mode == "w":
            index.unlink()
            index.symlink_to(outside)
        return real_open(file, mode, *args, **kwargs)

    with patch("builtins.open", swap_for_symlink):
        sync_module.sync_directory(wiki, "nested")
    assert outside.read_text() == "outside sentinel\n"

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    wiki = root / "wiki"
    nested = wiki / "nested"
    nested.mkdir(parents=True)
    page = nested / "page.md"
    page.write_text("---\ntype: note\n---\n")
    sync_module.sync_directory(wiki, "nested")
    page.unlink()
    index = nested / "index.md"
    user_file = nested / ".user-index.md"
    user_file.write_text("preserve me\n")
    real_rename = sync_module.os.rename

    def swap_before_quarantine(src, dst, *args, **kwargs):
        if src == "index.md":
            index.unlink()
            user_file.rename(index)
        return real_rename(src, dst, *args, **kwargs)

    with patch.object(sync_module.os, "rename", swap_before_quarantine):
        sync_module.sync_directory(wiki, "nested")
    assert index.read_text() == "preserve me\n"

print("wiki middleware boundary regressions PASS")
