#!/usr/bin/env bash
set -euo pipefail

hook=${1:?hook path required}
middleware=${2:?middleware path required}
hook=$(cd "$(dirname "$hook")" && pwd -P)/$(basename "$hook")
middleware=$(cd "$middleware" && pwd -P)
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
vault=$work/vault
mkdir -p "$vault/wiki" "$vault/.obsidian"
cd "$vault"
git init -q
git config user.name test
git config user.email test@example.invalid

cat >wiki/quickstart.md <<'EOF'
---
type: note
title: Quickstart
last_updated: 2026-01-01
---
# Quickstart
EOF
: >wiki/log.md
WIKI_MIDDLEWARE_DIR=$middleware python3 "$middleware/sync.py" . >/dev/null
git add wiki
git commit -qm baseline

# Claude file tools must be denied before they write protected wiki paths.
for blocked in wiki/index.md wiki/log.md wiki/.raw/secret.env; do
  result=$(printf '{"tool_name":"Write","tool_input":{"file_path":"%s"}}' "$blocked" |
    OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" prewrite)
  printf '%s' "$result" | jq -e '.hookSpecificOutput.permissionDecision == "deny"' >/dev/null
done
result=$(printf '%s' '{"tool_name":"Write","tool_input":{"file_path":"wiki/_plan.md"}}' |
  OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" prewrite)
[ -z "$result" ]
result=$(printf '%s' '{"tool_name":"NotebookEdit","tool_input":{"notebook_path":"scratch.ipynb"}}' |
  OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" prewrite)
[ -z "$result" ]

# A shell write is outside pre-tool coverage, but must never auto-commit.
mkdir -p wiki/.raw
printf 'fixture-not-a-secret\n' >wiki/.raw/secret.env
if OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware \
  bash "$hook" autocommit "$vault/wiki/.raw/secret.env" >/dev/null 2>&1; then
  echo "blocked wiki path was committed" >&2
  exit 1
fi
if git cat-file -e HEAD:wiki/.raw/secret.env 2>/dev/null; then
  echo "blocked wiki path appeared in HEAD" >&2
  exit 1
fi
rm wiki/.raw/secret.env
rmdir wiki/.raw

mkdir -p wiki/topic
cat >wiki/topic/new-page.md <<'EOF'
---
type: note
title: New Page
last_updated: 2026-01-02
---
# New Page
EOF
# A permitted direct sync attributes the exact generated bytes; lifecycle can
# safely commit those bytes with the changed page on the subsequent hook.
WIKI_MIDDLEWARE_DIR=$middleware python3 "$middleware/sync.py" . >/dev/null
before=$(git rev-list --count HEAD)
OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" autocommit "$vault/wiki/topic/new-page.md"
after=$(git rev-list --count HEAD)
[ "$after" -eq $((before + 1)) ]
[ -z "$(git status --porcelain)" ]
for expected in wiki/topic/new-page.md wiki/topic/index.md wiki/index.md wiki/log.md; do
  git diff-tree --no-commit-id --name-only -r HEAD | grep -Fx "$expected" >/dev/null
done

output=$(OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" autocommit "$vault/wiki/topic/new-page.md")
[ "$output" = clean ]
[ "$(git rev-list --count HEAD)" -eq "$after" ]

printf '\nOpt-out test.\n' >>wiki/topic/new-page.md
mkdir -p .vault-meta
touch .vault-meta/auto-commit.disabled
output=$(OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" autocommit "$vault/wiki/topic/new-page.md")
[ "$output" = disabled ]
[ "$(git rev-list --count HEAD)" -eq "$after" ]
[ -n "$(git status --porcelain -- wiki/topic/new-page.md)" ]
rm .vault-meta/auto-commit.disabled
OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware \
  bash "$hook" autocommit "$vault/wiki/topic/new-page.md" >/dev/null
after=$(git rev-list --count HEAD)
[ -z "$(git status --porcelain -- wiki)" ]

cat >wiki/topic/relative-page.md <<'EOF'
---
type: note
title: Relative Page
last_updated: 2026-01-02
---
# Relative Page
EOF
output=$(
  cd wiki/topic
  printf '%s' '{"tool_name":"Write","tool_input":{"file_path":"relative-page.md"}}' |
    OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" autocommit
)
[ "$output" = committed ]
git diff-tree --no-commit-id --name-only -r HEAD | grep -Fx wiki/topic/relative-page.md >/dev/null
after=$(git rev-list --count HEAD)

cat >wiki/invalid.md <<'EOF'
# Missing frontmatter
EOF
if OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" autocommit "$vault/wiki/invalid.md" >/dev/null 2>&1; then
  echo "invalid page was committed" >&2
  exit 1
fi
[ "$(git rev-list --count HEAD)" -eq "$after" ]
[ -n "$(git status --porcelain -- wiki/invalid.md)" ]
cat >wiki/invalid.md <<'EOF'
---
type: note
title: Repaired
last_updated: 2026-01-03
---
# Repaired
EOF
OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" autocommit "$vault/wiki/invalid.md"
[ -z "$(git status --porcelain -- wiki)" ]

printf 'baseline\n' >unrelated.txt
git add unrelated.txt
git commit -qm fixture
printf 'pre-existing change\n' >>unrelated.txt
cat >wiki/isolated.md <<'EOF'
---
type: note
title: Isolated
last_updated: 2026-01-04
---
# Isolated
EOF
OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" autocommit "$vault/wiki/isolated.md"
[ -z "$(git status --porcelain -- wiki)" ]
[ "$(git status --porcelain -- unrelated.txt)" = ' M unrelated.txt' ]
if git diff --cached --name-only | grep -q .; then
  echo "unrelated changes were staged" >&2
  exit 1
fi

# A direct sync may leave a verified generated index dirty in another subtree;
# commit only indexes attributed to the requested page's ancestor directories.
mkdir -p wiki/unrelated
cat >wiki/unrelated/page.md <<'EOF'
---
type: note
title: Unrelated Old
last_updated: 2026-01-04
---
# Unrelated Old
EOF
WIKI_MIDDLEWARE_DIR=$middleware python3 "$middleware/sync.py" . >/dev/null
git add wiki/unrelated/page.md wiki/unrelated/index.md wiki/index.md
git commit -qm 'unrelated baseline'
sed 's/Unrelated Old/Unrelated New/' wiki/unrelated/page.md >wiki/unrelated/page.tmp
mv wiki/unrelated/page.tmp wiki/unrelated/page.md
WIKI_MIDDLEWARE_DIR=$middleware python3 "$middleware/sync.py" . >/dev/null
git add wiki/unrelated/page.md
git commit -qm 'unrelated page edit'
[ -n "$(git status --porcelain -- wiki/unrelated/index.md)" ]
cat >wiki/topic/scoped.md <<'EOF'
---
type: note
title: Scoped Page
last_updated: 2026-01-04
---
# Scoped Page
EOF
OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" autocommit "$vault/wiki/topic/scoped.md" >/dev/null
[ -n "$(git status --porcelain -- wiki/unrelated/index.md)" ]
if git diff-tree --no-commit-id --name-only -r HEAD | grep -Fx 'wiki/unrelated/index.md' >/dev/null; then
  echo "unrelated generated index was absorbed into the page commit" >&2
  exit 1
fi
git restore --worktree -- wiki/unrelated/index.md

printf '\211PNG\r\n\032\nfixture' >'wiki/topic/diagram 1.png'
OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware \
  bash "$hook" autocommit "$vault/wiki/topic/diagram 1.png" >/dev/null
git diff-tree --no-commit-id --name-only -r HEAD | grep -Fx 'wiki/topic/diagram 1.png' >/dev/null
[ "$(git status --porcelain -- unrelated.txt)" = ' M unrelated.txt' ]
[ -z "$(git diff --cached --name-only)" ]
git restore --worktree -- unrelated.txt

cat >wiki/retry.md <<'EOF'
---
type: note
title: Retry
last_updated: 2026-01-05
---
# Retry
EOF
cat >.git/hooks/pre-commit <<'EOF'
#!/bin/sh
exit 1
EOF
chmod +x .git/hooks/pre-commit
if OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware \
  bash "$hook" autocommit "$vault/wiki/retry.md" >/dev/null 2>&1; then
  echo "rejecting pre-commit hook did not fail autocommit" >&2
  exit 1
fi
[ -n "$(git status --porcelain -- wiki/retry.md)" ]
if git cat-file -e HEAD:wiki/retry.md 2>/dev/null; then
  echo "failed autocommit unexpectedly committed retry page" >&2
  exit 1
fi
[ -z "$(git diff --cached --name-only)" ]
[ -n "$(git status --porcelain -- wiki/retry.md)" ]
[ -n "$(git status --porcelain -- wiki/index.md)" ]
retry_index_bytes=$(shasum -a 256 wiki/index.md | cut -d ' ' -f 1)
grep -Fq '[Retry](retry.md)' wiki/index.md
rm .git/hooks/pre-commit
OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware \
  bash "$hook" autocommit "$vault/wiki/retry.md" >/dev/null
[ -z "$(git status --porcelain -- wiki/retry.md wiki/index.md)" ]
[ -n "$(git status --porcelain -- wiki/unrelated/index.md)" ]
[ "$(shasum -a 256 <(git show HEAD:wiki/index.md) | cut -d ' ' -f 1)" = "$retry_index_bytes" ]
git restore --worktree -- wiki/unrelated/index.md
# OKF §9 log shape: H1 title, YYYY-MM-DD date heading, one prose bullet linking
# the retry page bundle-relative. No legacy `## <datetime> | paths` line.
[ "$(head -1 wiki/log.md)" = '# Directory Update Log' ]
grep -qE '^## [0-9]{4}-[0-9]{2}-[0-9]{2}$' wiki/log.md
[ "$(grep -Fc '(/retry.md)' wiki/log.md)" -eq 1 ]
if grep -qE '^## .*\|' wiki/log.md; then
  echo "log.md still contains a legacy '## <datetime> | paths' heading" >&2
  exit 1
fi
[ -z "$(git status --porcelain)" ]

# Dedicated postwrite phase refreshes navigation immediately without committing.
cat >wiki/postwrite.md <<'EOF'
---
type: note
title: Postwrite Page
last_updated: 2026-01-11
---
# Postwrite Page
EOF
output=$(OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" postwrite "$vault/wiki/postwrite.md")
[ "$output" = synced ]
[ -n "$(git status --porcelain -- wiki/postwrite.md)" ]
[ -n "$(git status --porcelain -- wiki/index.md)" ]
grep -Fq '[Postwrite Page](postwrite.md)' wiki/index.md
if git cat-file -e HEAD:wiki/postwrite.md 2>/dev/null; then
  echo "postwrite phase committed instead of deferring commit" >&2
  exit 1
fi
OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" autocommit "$vault/wiki/postwrite.md" >/dev/null
[ -z "$(git status --porcelain -- wiki/postwrite.md wiki/index.md)" ]
[ -n "$(git status --porcelain -- wiki/unrelated/index.md)" ]

# A partial index-sync failure preserves the valid page and generated output;
# a subsequent lifecycle retry settles both without absorbing unrelated pages.
cat >wiki/topic/partial-sync.md <<'EOF'
---
type: note
title: Partial Sync Retry
last_updated: 2026-01-10
---
# Partial Sync Retry
EOF
fault_middleware=$work/fault-middleware
mkdir -p "$fault_middleware"
cp -R "$middleware/." "$fault_middleware/"
cat >"$fault_middleware/sync.py" <<EOF
#!/usr/bin/env python3
import os, subprocess, sys
marker = "$work/sync-failed-once"
if not os.path.exists(marker):
    subprocess.run([sys.executable, "$middleware/sync.py", sys.argv[1], "--dir", "topic"], check=True)
    open(marker, "w").close()
    raise SystemExit(1)
subprocess.run([sys.executable, "$middleware/sync.py", *sys.argv[1:]], check=True)
EOF
if OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$fault_middleware bash "$hook" autocommit "$vault/wiki/topic/partial-sync.md" >/dev/null 2>&1; then
  echo "injected partial sync failure was not reported" >&2
  exit 1
fi
[ -f "$work/sync-failed-once" ]
[ -n "$(git status --porcelain -- wiki/topic/partial-sync.md)" ]
[ -n "$(git status --porcelain -- wiki/topic/index.md)" ]
grep -Fq '[Partial Sync Retry](partial-sync.md)' wiki/topic/index.md
OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$fault_middleware bash "$hook" autocommit "$vault/wiki/topic/partial-sync.md" >/dev/null
[ -z "$(git status --porcelain -- wiki/topic/partial-sync.md wiki/topic/index.md)" ]
[ -n "$(git status --porcelain -- wiki/unrelated/index.md)" ]

# Deleted file should be skipped gracefully (not abort the hook).
cat >wiki/ephemeral.md <<'EOF'
---
type: note
title: Ephemeral
last_updated: 2026-01-06
---
# Ephemeral
EOF
rm wiki/ephemeral.md
output=$(OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" autocommit "$vault/wiki/ephemeral.md")
[ "$output" = clean ]

# _plan.md should be skipped (ephemeral planning file, no OKF frontmatter).
cat >wiki/_plan.md <<'EOF'
# Planning notes (no frontmatter)
EOF
output=$(OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" autocommit "$vault/wiki/_plan.md")
[ "$output" = clean ]
rm wiki/_plan.md

# sync.py lists .base (Obsidian Bases) views, so a base-only directory still
# gets a generated index and its parent directory link never dangles.
cat >wiki/topic/board.base <<'EOF'
filters: []
EOF
WIKI_MIDDLEWARE_DIR=$middleware python3 "$middleware/sync.py" . >/dev/null
grep -qx '# Bases' wiki/topic/index.md
grep -Fq '[board](board.base)' wiki/topic/index.md
rm wiki/topic/board.base
WIKI_MIDDLEWARE_DIR=$middleware python3 "$middleware/sync.py" . >/dev/null

mkdir "$work/outside"
output=$(cd "$work/outside" && OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" start)
[ -z "$output" ]

# Structured middleware conflicts must reach the caller with the recoverable path.
mkdir -p wiki/conflict
cat >wiki/conflict/page.md <<'EOF'
---
type: note
title: Conflict
---
EOF
printf 'handwritten index\n' >wiki/conflict/index.md
if diagnostic=$(OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" postwrite "$vault/wiki/conflict/page.md" 2>&1); then
  echo "postwrite accepted a handwritten generated-index conflict" >&2
  exit 1
fi
printf '%s' "$diagnostic" | grep -F 'wiki/conflict/index.md' >/dev/null
printf '%s' "$diagnostic" | grep -F 'unmarked index differs' >/dev/null
[ "$(cat wiki/conflict/index.md)" = 'handwritten index' ]
rm -rf wiki/conflict

properties=$work/properties.json
printf '{"vaultPath":"%s","features":{"guard":false,"toc":false,"autoCommit":false,"retrievalRefresh":false}}\n' "$vault" >"$properties"
output=$(OBSIDIAN_AGENT_CONFIG=$properties WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" start)
[ -z "$output" ]
output=$(printf '%s' '{"tool_name":"Write","tool_input":{"file_path":"wiki/index.md"}}' |
  OBSIDIAN_AGENT_CONFIG=$properties WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" prewrite)
[ -z "$output" ]
output=$(OBSIDIAN_AGENT_CONFIG=$properties WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" autocommit "$vault/wiki/quickstart.md")
[ "$output" = disabled ]
# Disabled auto-commit still validates the page and refreshes navigation.
cat >wiki/topic/disabled.md <<'EOF'
---
type: note
title: Disabled lifecycle
last_updated: 2026-01-08
---
# Disabled lifecycle
EOF
output=$(OBSIDIAN_AGENT_CONFIG=$properties WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" autocommit "$vault/wiki/topic/disabled.md")
[ "$output" = disabled ]
grep -Fq '[Disabled lifecycle](disabled.md)' wiki/topic/index.md
cat >wiki/topic/disabled-invalid.md <<'EOF'
# Invalid while auto-commit disabled
EOF
if OBSIDIAN_AGENT_CONFIG=$properties WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" autocommit "$vault/wiki/topic/disabled-invalid.md" >/dev/null 2>&1; then
  echo "invalid page passed lifecycle with auto-commit disabled" >&2
  exit 1
fi
rm -f "$properties"

# Empty invocation overrides fall back to the same valid config as Pi. Invalid
# feature flags retain the known boundary but fail closed on active operations.
printf '{"vaultPath":"%s","features":{"toc":true}}\n' "$vault" >"$properties"
output=$(OBSIDIAN_AGENT_CONFIG=$properties OBSIDIAN_VAULT_PATH='' WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" start)
printf '%s' "$output" | grep -F 'Quickstart' >/dev/null
printf '{"vaultPath":"%s","features":{"guard":"false"}}\n' "$vault" >"$properties"
if printf '%s' '{"tool_name":"Write","tool_input":{"file_path":"wiki/index.md"}}' |
  OBSIDIAN_AGENT_CONFIG=$properties OBSIDIAN_VAULT_PATH='' WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" prewrite |
  jq -e '.hookSpecificOutput.permissionDecision == "deny"' >/dev/null; then :; else
  echo "invalid guard flag did not deny wiki writes" >&2
  exit 1
fi
if OBSIDIAN_AGENT_CONFIG=$properties OBSIDIAN_VAULT_PATH='' WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" guard wiki/quickstart.md >/dev/null 2>&1; then
  echo "guard accepted invalid configuration" >&2
  exit 1
fi
if OBSIDIAN_AGENT_CONFIG=$properties OBSIDIAN_VAULT_PATH='' WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" postwrite "$vault/wiki/quickstart.md" >/dev/null 2>&1; then
  echo "postwrite accepted invalid configuration" >&2
  exit 1
fi
output=$(OBSIDIAN_AGENT_CONFIG=$properties OBSIDIAN_VAULT_PATH='' WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" start)
printf '%s' "$output" | grep -F 'explicit approval' >/dev/null

# Repair permission is limited to the exact selected regular config file.
# Wiki writes stay denied until revalidation, and unrelated files are untouched.
printf '{"vaultPath":"%s","features":{"guard":"false"},"custom":"preserve"}\n' "$vault" >"$properties"
result=$(printf '{"tool_name":"Write","tool_input":{"file_path":"%s"}}' "$properties" |
  OBSIDIAN_AGENT_CONFIG=$properties WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" prewrite)
[ -z "$result" ]
printf 'leave untouched\n' >"$work/unrelated-settings.json"
result=$(printf '{"tool_name":"Write","tool_input":{"file_path":"%s"}}' "$work/unrelated-settings.json" |
  OBSIDIAN_AGENT_CONFIG=$properties WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" prewrite)
printf '%s' "$result" | jq -e '.hookSpecificOutput.permissionDecision == "deny"' >/dev/null
[ "$(cat "$work/unrelated-settings.json")" = 'leave untouched' ]
ln -s "$properties" "$work/config-alias.json"
result=$(printf '{"tool_name":"Write","tool_input":{"file_path":"%s"}}' "$work/config-alias.json" |
  OBSIDIAN_AGENT_CONFIG=$properties WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" prewrite)
printf '%s' "$result" | jq -e '.hookSpecificOutput.permissionDecision == "deny"' >/dev/null
result=$(printf '%s' '{"tool_name":"Write","tool_input":{"file_path":"wiki/quickstart.md"}}' |
  OBSIDIAN_AGENT_CONFIG=$properties WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" prewrite)
printf '%s' "$result" | jq -e '.hookSpecificOutput.permissionDecision == "deny"' >/dev/null
printf '{"vaultPath":"%s","features":{"guard":true},"custom":"preserve"}\n' "$vault" >"$properties"
result=$(printf '%s' '{"tool_name":"Write","tool_input":{"file_path":"wiki/quickstart.md"}}' |
  OBSIDIAN_AGENT_CONFIG=$properties WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" prewrite)
[ -z "$result" ]
jq -e '.custom == "preserve"' "$properties" >/dev/null
rm -f "$work/config-alias.json"

# Null/missing vaultPath is intentionally inactive; malformed config and a
# non-string configured path fail closed instead of silently disabling hooks.
printf '{"vaultPath":null}\n' >"$properties"
[ -z "$(OBSIDIAN_AGENT_CONFIG=$properties WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" start)" ]
printf '{"features":{}}\n' >"$properties"
[ -z "$(OBSIDIAN_AGENT_CONFIG=$properties WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" start)" ]
printf '{"vaultPath":"/wrong/vault"}\n' >"$properties"
output=$(OBSIDIAN_AGENT_CONFIG=$properties OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" start)
printf '%s' "$output" | grep -F 'Quickstart' >/dev/null
printf '{"vaultPath":42}\n' >"$properties"
if OBSIDIAN_AGENT_CONFIG=$properties WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" start >/dev/null 2>&1; then
  echo "wrong-type vaultPath did not fail" >&2
  exit 1
fi
printf '[1,2]\n' >"$properties"
if OBSIDIAN_AGENT_CONFIG=$properties WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" start >/dev/null 2>&1; then
  echo "non-object config did not fail" >&2
  exit 1
fi
printf '{invalid json\n' >"$properties"
if OBSIDIAN_AGENT_CONFIG=$properties WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" start >/dev/null 2>&1; then
  echo "malformed config did not fail" >&2
  exit 1
fi

# Shutdown must not mutate indexes while the selected config is invalid.
cat >wiki/shutdown-config.md <<'EOF'
---
type: note
title: Shutdown Config Original
last_updated: 2026-01-09
---
# Shutdown Config Original
EOF
WIKI_MIDDLEWARE_DIR=$middleware python3 "$middleware/sync.py" . >/dev/null
git add wiki/shutdown-config.md wiki/index.md
git commit -qm 'shutdown config baseline'
sed 's/Shutdown Config Original/Shutdown Config Repaired/' wiki/shutdown-config.md >wiki/shutdown-config.tmp
mv wiki/shutdown-config.tmp wiki/shutdown-config.md
page_before=$(shasum -a 256 wiki/shutdown-config.md | cut -d ' ' -f 1)
index_before=$(shasum -a 256 wiki/index.md | cut -d ' ' -f 1)
printf '{"vaultPath":"%s","features":{"guard":"false"}}\n' "$vault" >"$properties"
if diagnostic=$(OBSIDIAN_AGENT_CONFIG=$properties OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" stop 2>&1); then
  echo "shutdown synchronized with invalid configuration" >&2
  exit 1
fi
printf '%s' "$diagnostic" | grep -Eiq 'invalid|repair'
[ "$(shasum -a 256 wiki/shutdown-config.md | cut -d ' ' -f 1)" = "$page_before" ]
[ "$(shasum -a 256 wiki/index.md | cut -d ' ' -f 1)" = "$index_before" ]
# Repair only the fixture config, then shutdown synchronization may resume.
printf '{"vaultPath":"%s","features":{"guard":true,"autoCommit":false}}\n' "$vault" >"$properties"
OBSIDIAN_AGENT_CONFIG=$properties OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" stop
grep -Fq '[Shutdown Config Repaired](shutdown-config.md)' wiki/index.md
git add wiki/shutdown-config.md wiki/index.md
git commit -qm 'repaired shutdown config fixture'

# Keep auto-commit explicitly disabled through shutdown; generated dirty indexes
# are expected state, not an unsettled-commit warning.
printf '{"vaultPath":"%s","features":{"autoCommit":false}}
' "$vault" >"$properties"
export OBSIDIAN_AGENT_CONFIG=$properties

# A non-Git vault still validates and synchronizes pages; lack of Git is normal.
plain=$work/non-git-vault
mkdir -p "$plain/wiki"
cat >"$plain/wiki/page.md" <<'EOF'
---
type: note
title: Non-Git Page
last_updated: 2026-01-09
---
# Non-Git Page
EOF
output=$(cd "$plain" && OBSIDIAN_AGENT_CONFIG=$work/no-properties.json OBSIDIAN_VAULT_PATH=$plain WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" autocommit "$plain/wiki/page.md")
[ "$output" = clean ]
grep -Fq '[Non-Git Page](page.md)' "$plain/wiki/index.md"
# A non-Git vault transitioning into Git must report the existing runtime
# metadata and safe remediation without changing its generated index.
plain_index_before=$(shasum -a 256 "$plain/wiki/index.md" | awk '{print $1}')
git init -q "$plain"
if transition_diagnostic=$(cd "$plain" && OBSIDIAN_VAULT_PATH=$plain WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" postwrite "$plain/wiki/page.md" 2>&1); then
  echo "non-Git to Git transition accepted visible ownership metadata" >&2
  exit 1
fi
printf '%s' "$transition_diagnostic" | grep -F "$plain/.vault-meta/okf-index-ownership.json" >/dev/null
printf '%s' "$transition_diagnostic" | grep -F "$plain/.vault-meta/okf-index-ownership.lock" >/dev/null
printf '%s' "$transition_diagnostic" | grep -F 'safely preserve the files' >/dev/null
printf '%s' "$transition_diagnostic" | grep -F 'exact .vault-meta ignore rule' >/dev/null
printf '%s' "$transition_diagnostic" | grep -F 'untrack any tracked file' >/dev/null
if printf '%s' "$transition_diagnostic" | grep -Eiq 'jq:|parse error'; then
  echo "non-Git to Git transition emitted JSON parser noise" >&2
  exit 1
fi
[ "$(shasum -a 256 "$plain/wiki/index.md" | awk '{print $1}')" = "$plain_index_before" ]

# Retrieval helpers are optional and derived state is never staged/committed.
rm -rf scripts .vault-meta
OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" stop
mkdir -p scripts
printf '#!/bin/sh\nexit 1\n' >scripts/contextual-prefix.py
printf '#!/bin/sh\nexit 1\n' >scripts/bm25-index.py
OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" stop 2>"$work/retrieval-warning"
grep -q 'retrieval index refresh failed' "$work/retrieval-warning"
repo=$(cd "$(dirname "$hook")/.." && pwd -P)
cp "$repo/scripts/contextual-prefix.py" scripts/contextual-prefix.py
cp "$repo/scripts/bm25-index.py" scripts/bm25-index.py
OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" stop
[ -f .vault-meta/retrieval/bm25.json ]
[ -z "$(git diff --cached --name-only)" ]
if git cat-file -e HEAD:.vault-meta/retrieval/bm25.json 2>/dev/null; then
  echo "retrieval cache was committed" >&2
  exit 1
fi
# A pre-existing tracked cache is warned about, but remains unstaged.
git add .vault-meta/retrieval/bm25.json
git commit -qm 'tracked retrieval cache fixture'
cat >wiki/cache-fixture.md <<'EOF'
---
type: note
title: Cache Fixture
last_updated: 2026-01-07
---
# Cache Fixture
EOF
WIKI_MIDDLEWARE_DIR=$middleware python3 "$middleware/sync.py" . >/dev/null
# Include page and generated navigation as committed baseline before shutdown.
git add wiki
git commit -qm 'cache fixture page'
OBSIDIAN_VAULT_PATH=$vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" stop 2>"$work/tracked-cache-warning"
grep -q 'retrieval cache is tracked' "$work/tracked-cache-warning"
[ -n "$(git diff -- .vault-meta/retrieval/bm25.json)" ]
[ -z "$(git diff --cached --name-only)" ]

# A vault without its own Git repository still syncs indexes and refreshes its
# optional retrieval cache; a containing repository must never be treated as it.
parent=$work/parent-repo
no_git_vault=$parent/nested-vault
mkdir -p "$no_git_vault/wiki" "$no_git_vault/scripts"
git init -q "$parent"
git -C "$parent" config user.name test
git -C "$parent" config user.email test@example.invalid
printf 'parent sentinel\n' >"$parent/sentinel.txt"
git -C "$parent" add sentinel.txt
git -C "$parent" commit -qm baseline
cp "$repo/scripts/contextual-prefix.py" "$no_git_vault/scripts/"
cp "$repo/scripts/bm25-index.py" "$no_git_vault/scripts/"
cat >"$no_git_vault/wiki/no-git-page.md" <<'EOF'
---
type: note
title: No Git Page
last_updated: 2026-01-08
---
# No Git Page
EOF
# An unconfigured nested vault must refuse before creating public indexes or
# runtime ownership metadata; the hook never edits a containing repo's ignores.
parent_status_before=$(git -C "$parent" status --porcelain)
parent_head_before=$(git -C "$parent" rev-parse HEAD)
if nested_diagnostic=$(cd "$no_git_vault" && OBSIDIAN_VAULT_PATH=$no_git_vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" stop 2>&1); then
  echo "nested vault accepted unignored ownership metadata" >&2
  exit 1
fi
printf '%s' "$nested_diagnostic" | grep -F 'shutdown index synchronization failed' >/dev/null
if nested_postwrite=$(cd "$no_git_vault" && OBSIDIAN_VAULT_PATH=$no_git_vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" postwrite "$no_git_vault/wiki/no-git-page.md" 2>&1); then
  echo "nested vault accepted unignored ownership metadata during postwrite" >&2
  exit 1
fi
printf '%s' "$nested_postwrite" | grep -F "$no_git_vault/.vault-meta/okf-index-ownership.json" >/dev/null
printf '%s' "$nested_postwrite" | grep -F "$no_git_vault/.vault-meta/okf-index-ownership.lock" >/dev/null
printf '%s' "$nested_postwrite" | grep -F 'safely preserve the files' >/dev/null
printf '%s' "$nested_postwrite" | grep -F 'exact .vault-meta ignore rule' >/dev/null
printf '%s' "$nested_postwrite" | grep -F 'untrack any tracked file' >/dev/null
if printf '%s' "$nested_postwrite" | grep -Eiq 'jq:|parse error'; then
  echo "nested exclusion refusal emitted JSON parser noise" >&2
  exit 1
fi
[ ! -e "$no_git_vault/wiki/index.md" ]
[ ! -e "$no_git_vault/.vault-meta/okf-index-ownership.json" ]
[ ! -e "$no_git_vault/.vault-meta/okf-index-ownership.lock" ]
[ "$(git -C "$parent" status --porcelain)" = "$parent_status_before" ]
[ "$(git -C "$parent" rev-parse HEAD)" = "$parent_head_before" ]
[ -z "$(git -C "$parent" diff --cached --name-only)" ]
[ -z "$(git -C "$parent" diff --name-only)" ]
# The test owner explicitly opts this synthetic nested vault into the parent's
# ignore policy before retrying; production never edits repository excludes.
printf '/nested-vault/.vault-meta/okf-index-ownership.json\n/nested-vault/.vault-meta/okf-index-ownership.lock\n' \
  >>"$parent/.git/info/exclude"
git -C "$parent" check-ignore -q -- nested-vault/.vault-meta/okf-index-ownership.json
git -C "$parent" check-ignore -q -- nested-vault/.vault-meta/okf-index-ownership.lock
(cd "$no_git_vault" && OBSIDIAN_VAULT_PATH=$no_git_vault WIKI_MIDDLEWARE_DIR=$middleware bash "$hook" stop)
[ -f "$no_git_vault/wiki/index.md" ]
[ -f "$no_git_vault/.vault-meta/retrieval/bm25.json" ]
[ ! -e "$no_git_vault/.git" ]
[ -z "$(git -C "$parent" diff --cached --name-only)" ]
[ -z "$(git -C "$parent" diff --name-only)" ]
