#!/usr/bin/env python3
"""Boundary and content regressions for the wiki Python middleware."""

import json
from pathlib import Path
import subprocess
import sys
import tempfile
from unittest.mock import patch

middleware = Path(sys.argv[1]).resolve()


def run(script: Path, *args: str, ok: bool = True) -> subprocess.CompletedProcess:
    result = subprocess.run(
        [sys.executable, str(script), *map(str, args)],
        text=True, capture_output=True, check=False,
    )
    if ok and result.returncode:
        raise AssertionError(f"{script.name} unexpectedly failed: {result.stderr}")
    if not ok and result.returncode == 0:
        raise AssertionError(f"{script.name} unexpectedly succeeded: {args}")
    return result


with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    wiki = root / "wiki"
    topic = wiki / "topic"
    outside = root / "outside"
    topic.mkdir(parents=True)
    outside.mkdir()
    (wiki / ".raw").mkdir()
    page = topic / "page.md"
    page.write_text('---\ntype: note\ntitle: "A [link]"\n'
                    'description: >\n  first line\n  second line\n---\n[[dest]]\n')
    (wiki / "dest.md").write_text("---\ntype: note\ntitle: Dest\n---\n")
    foreign = outside / "foreign.md"
    foreign.write_text("---\ntype: note\n---\n[[dest]]\n")
    (wiki / "alias").symlink_to(outside, target_is_directory=True)
    (wiki / "foreign.md").symlink_to(foreign)

    guard = middleware / "guard.py"
    run(guard, root, "wiki/topic/page.md")
    run(guard, root, "wiki/_plan.md")
    run(guard, "--if-wiki", root, "outside/other.md")
    for blocked in (".raw/secret.env", ".obsidian/app.json", ".vault-meta/cache", ".git/config",
                    "wiki/index.md", "wiki/topic/index.md", "wiki/topic/INDEX.MD", "wiki/log.md",
                    "wiki/topic/log.md", "wiki/topic/Log.MD", "wiki/.raw/secret.env",
                    "wiki/alias/new.md", "wiki/foreign.md", "wiki/../outside/foreign.md"):
        run(guard, root, blocked, ok=False)
    # Destination-based protections apply even when the caller is in another workspace.
    caller = Path(temp) / "caller"
    caller.mkdir()
    run(guard, "--if-wiki", root, str(root / ".obsidian" / "app.json"), ok=False)
    run(guard, "--if-wiki", root, str(root / "wiki" / "topic" / "page.md"))
    # Protected selected-vault roots remain blocked when symlinked outside or
    # into an otherwise writable area of the selected vault.
    unprotected = root / "unprotected"
    unprotected.mkdir()
    for protected_name in (".raw", ".obsidian", ".vault-meta", ".git"):
        link = root / protected_name
        for destination in (outside, unprotected):
            sentinel = destination / f"{protected_name[1:]}-sentinel.json"
            sentinel.write_text("must remain protected\\n")
            link.symlink_to(destination, target_is_directory=True)
            run(guard, "--if-wiki", root, str(link / sentinel.name), ok=False)
            assert sentinel.read_text() == "must remain protected\\n"
            link.unlink()
    # The supported macOS /var prefix alias remains recognized for normal and protected paths.
    alias_root = str(root.resolve())
    if sys.platform == "darwin" and alias_root.startswith("/private/var/"):
        alias_root = alias_root.replace("/private/var/", "/var/", 1)
        assert Path(alias_root).resolve() == root.resolve()
        run(guard, "--if-wiki", alias_root, str(Path(alias_root) / ".obsidian" / "app.json"), ok=False)
        run(guard, "--if-wiki", alias_root, str(Path(alias_root) / "wiki/topic/page.md"))
    run(guard, "--if-wiki", root, page)

    validator = middleware / "validate.py"
    run(validator, page)
    invalid = wiki / "invalid.md"
    invalid.write_text("---\ntype: note\n---not-a-delimiter\n")
    run(validator, invalid, ok=False)
    invalid.unlink()

    sync = middleware / "sync.py"
    for directory in ("../outside", "alias"):
        run(sync, root, "--dir", directory, ok=False)
    assert not (outside / "index.md").exists()
    run(sync, root)
    index = (wiki / "index.md").read_text()
    assert "[alias/]" not in index and "[foreign]" not in index
    assert "[A \\[link\\]](page.md) - first line second line" in (topic / "index.md").read_text()
    assert "<!-- Generated by OKF middleware; do not edit. -->" in index
    assert "<!-- Generated by OKF middleware; do not edit. -->" in (topic / "index.md").read_text()
    assert "[topic/](topic/)" in index
    lint = json.loads(run(middleware / "lint.py", root).stdout)
    assert not lint["stale_index_entries"] and not lint["dead_links"]


with tempfile.TemporaryDirectory() as temp:
    sys.path.insert(0, str(middleware))
    import sync as sync_module

    root = Path(temp) / "vault"
    wiki = root / "wiki"
    nested = wiki / "nested"
    nested.mkdir(parents=True)
    page = nested / "page.md"
    page.write_text("---\ntype: note\n---\n")
    outside = root / "outside.md"
    outside.write_text("user data must survive\\n")
    (nested / "index.md").symlink_to(outside)

    sync = middleware / "sync.py"
    result = run(sync, root, "--dry-run", ok=False)
    assert outside.read_text() == "user data must survive\\n"
    assert "[ERROR]" in result.stdout
    result = run(sync, root, ok=False)
    assert outside.read_text() == "user data must survive\\n"
    assert "[ERROR]" in result.stdout

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    nested = root / "wiki" / "nested"
    nested.mkdir(parents=True)
    (nested / "page.md").write_text("---\ntype: note\n---\n")
    (nested / "index.md").mkdir()

    sync = middleware / "sync.py"
    result = run(sync, root, "--dir", "nested", ok=False)
    assert "[ERROR]" in result.stdout
    result = run(sync, root, ok=False)
    assert "[ERROR]" in result.stdout

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    nested = root / "wiki" / "nested"
    nested.mkdir(parents=True)
    (nested / "page.md").write_text("---\\ntype: note\\n---\\n")
    index = nested / "index.md"
    original = "Handwritten content\\n"
    index.write_text(original)
    sync = middleware / "sync.py"
    result = run(sync, root, "--dir", "nested", ok=False)
    assert "unmarked index differs" in result.stdout
    assert index.read_text() == original
    result = run(sync, root, ok=False)
    assert "unmarked index differs" in result.stdout
    assert index.read_text() == original

    index.unlink()
    run(sync, root, "--dir", "nested")
    assert "<!-- Generated by OKF middleware; do not edit. -->" in index.read_text()
    (nested / "another.md").write_text("---\\ntype: note\\n---\\n")
    run(sync, root, "--dir", "nested")
    generated = index.read_text()
    assert "(another.md)" in generated
    index.write_text(generated.replace(
        "<!-- Generated by OKF middleware; do not edit. -->\n", "", 1))
    legacy_bytes = index.read_bytes()
    run(sync, root, "--dir", "nested")
    assert index.read_bytes() == legacy_bytes

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    wiki = root / "wiki"
    wiki.mkdir(parents=True)
    page = wiki / "page.md"
    page.write_text('---\ntype: note\ntitle: Original\n---\n')
    sync = middleware / "sync.py"
    run(sync, root)
    index = wiki / "index.md"
    index.write_text(index.read_text() + "\nuser-authored navigation\n")
    expected = index.read_bytes()
    page.write_text('---\ntype: note\ntitle: Updated\n---\n')
    result = run(sync, root, ok=False)
    assert "unowned dirty bytes" in result.stdout
    assert index.read_bytes() == expected

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    wiki = root / "wiki"
    wiki.mkdir(parents=True)
    page = wiki / "page.md"
    page.write_text('---\ntype: note\ntitle: Original\n---\n')
    sync = middleware / "sync.py"
    subprocess.run(["git", "init", "-q", str(root)], check=True)
    subprocess.run(["git", "-C", str(root), "config", "user.name", "test"], check=True)
    subprocess.run(["git", "-C", str(root), "config", "user.email", "test@example.invalid"], check=True)
    run(sync, root)
    subprocess.run(["git", "-C", str(root), "add", "wiki"], check=True)
    subprocess.run(["git", "-C", str(root), "commit", "-qm", "baseline"], check=True)

    page.write_text('---\ntype: note\ntitle: Updated\n---\n')
    structured = json.loads(run(sync, root, "--json").stdout)
    assert any(change["path"] == "wiki/index.md" and change["before"] and change["after"]
               for change in structured["changes"])
    metadata_dir = Path(subprocess.check_output(
        ["git", "-C", str(root), "rev-parse", "--absolute-git-dir"], text=True).strip())
    assert (metadata_dir / "okf-index-ownership.json").exists()
    assert not (root / "okf-index-ownership.json").exists()

    # A marker is not ownership: preserve a relevant user-edited index even
    # when the marker remains and the page makes that directory relevant.
    index = wiki / "index.md"
    owner_inode = index.stat().st_ino
    forged = index.read_text() + "\nmanual-index-note\n"
    index.write_text(forged)
    assert index.stat().st_ino == owner_inode, "same-inode content change injection did not hold inode"
    page.write_text('---\ntype: note\ntitle: Newer\n---\n')
    result = run(sync, root, ok=False)
    assert "unowned dirty bytes" in result.stdout
    assert index.read_text() == forged

    # Once attributed, even an in-place edit that preserves the inode invalidates
    # the journal fingerprint and cannot be silently regenerated over.
    # Restore the clean committed preimage, then let middleware generate and
    # journal a fresh postimage before mutating that same inode.
    subprocess.run(["git", "-C", str(root), "checkout", "HEAD", "--", "wiki/index.md"], check=True)
    page.write_text('---\ntype: note\ntitle: Final\n---\n')
    run(sync, root)
    generated = index.read_bytes()
    inode = index.stat().st_ino
    index.write_bytes(generated + b"\nuser edit in place\n")
    assert index.stat().st_ino == inode
    edited = index.read_bytes()
    page.write_text('---\ntype: note\ntitle: Another\n---\n')
    result = run(sync, root, ok=False)
    assert "unowned dirty bytes" in result.stdout
    assert index.read_bytes() == edited

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    wiki = root / "wiki"
    wiki.mkdir(parents=True)
    page = wiki / "page.md"
    page.write_text('---\ntype: note\ntitle: Initial\n---\n')
    subprocess.run(["git", "init", "-q", str(root)], check=True)
    subprocess.run(["git", "-C", str(root), "config", "user.name", "test"], check=True)
    subprocess.run(["git", "-C", str(root), "config", "user.email", "test@example.invalid"], check=True)
    subprocess.run(["git", "-C", str(root), "add", "wiki/page.md"], check=True)
    subprocess.run(["git", "-C", str(root), "commit", "-qm", "page baseline"], check=True)
    index = wiki / "index.md"
    forged = "<!-- Generated by OKF middleware; do not edit. -->\nforged output\n"
    index.write_text(forged)
    page.write_text('---\ntype: note\ntitle: Updated\n---\n')
    result = run(middleware / "sync.py", root, ok=False)
    assert "unowned dirty bytes" in result.stdout
    assert index.read_text() == forged

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    wiki = root / "wiki"
    wiki.mkdir(parents=True)
    page = wiki / "page.md"
    page.write_text('---\ntype: note\ntitle: Initial\n---\n')
    subprocess.run(["git", "init", "-q", str(root)], check=True)
    subprocess.run(["git", "-C", str(root), "config", "user.name", "test"], check=True)
    subprocess.run(["git", "-C", str(root), "config", "user.email", "test@example.invalid"], check=True)
    run(middleware / "sync.py", root)
    outside = Path(temp) / "outside-journal.json"
    outside.write_text("preserve journal target\\n")
    metadata_dir = Path(subprocess.check_output(
        ["git", "-C", str(root), "rev-parse", "--absolute-git-dir"], text=True).strip())
    (metadata_dir / "okf-index-ownership.json").unlink()
    (metadata_dir / "okf-index-ownership.json").symlink_to(outside)
    page.write_text('---\ntype: note\ntitle: Updated\n---\n')
    result = run(middleware / "sync.py", root, ok=False)
    assert outside.read_text() == "preserve journal target\\n"
    assert (metadata_dir / "okf-index-ownership.json").is_symlink()
    assert "ERROR" in result.stdout

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    empty = root / "wiki" / "empty"
    empty.mkdir(parents=True)
    index = empty / "index.md"
    index.write_text("handwritten index\\n")
    result = run(middleware / "sync.py", root, ok=False)
    assert "unmarked index" in result.stdout
    assert index.read_text() == "handwritten index\\n"

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    wiki = root / "wiki"
    wiki.mkdir(parents=True)
    page = wiki / "page.md"
    page.write_text('---\ntype: note\ntitle: Initial\n---\n')
    run(middleware / "sync.py", root)
    journal = root / ".vault-meta/okf-index-ownership.json"
    lock = root / ".vault-meta/okf-index-ownership.lock"
    assert journal.is_file() and lock.is_file()
    subprocess.run(["git", "init", "-q", str(root)], check=True)
    page.write_text('---\ntype: note\ntitle: Updated\n---\n')
    index_before = (wiki / "index.md").read_bytes()
    result = run(middleware / "sync.py", root, "--json", ok=False)
    diagnostic = json.loads(result.stdout)
    assert len(diagnostic["results"]) == 1
    assert diagnostic["results"][0]["status"] == "ERROR"
    assert diagnostic["results"][0]["path"] == ".vault-meta"
    detail = diagnostic["results"][0]["detail"]
    assert "unignored ownership metadata" in detail
    assert str(journal) in detail and str(lock) in detail
    assert "safely preserve the files" in detail
    assert "exact .vault-meta ignore rule" in detail
    assert "untrack any tracked file" in detail
    assert diagnostic["changes"] == []
    assert (wiki / "index.md").read_bytes() == index_before
    assert journal.is_file() and lock.is_file()

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    wiki = root / "wiki"
    wiki.mkdir(parents=True)
    page = wiki / "page.md"
    page.write_text('---\ntype: note\ntitle: Initial\n---\n')
    run(middleware / "sync.py", root)
    journal = root / ".vault-meta/okf-index-ownership.json"
    subprocess.run(["git", "init", "-q", str(root)], check=True)
    (root / ".gitignore").write_text("/.vault-meta/\n")
    page.write_text('---\ntype: note\ntitle: Updated\n---\n')
    run(middleware / "sync.py", root)
    assert "[Updated](page.md)" in (wiki / "index.md").read_text()
    assert journal.is_file()

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    wiki = root / "wiki"
    wiki.mkdir(parents=True)
    page = wiki / "page.md"
    page.write_text('---\ntype: note\ntitle: Initial\n---\n')
    run(middleware / "sync.py", root)
    subprocess.run(["git", "init", "-q", str(root)], check=True)
    subprocess.run(["git", "-C", str(root), "add", ".vault-meta/okf-index-ownership.json"], check=True)
    result = run(middleware / "sync.py", root, ok=False)
    assert "tracked ownership metadata" in result.stdout

with tempfile.TemporaryDirectory() as temp:
    repository = Path(temp) / "repository"
    nested = repository / "nested-vault"
    (nested / "wiki").mkdir(parents=True)
    page = nested / "wiki/page.md"
    page.write_text('---\ntype: note\ntitle: Initial\n---\n')
    subprocess.run(["git", "init", "-q", str(repository)], check=True)
    result = run(middleware / "sync.py", nested, ok=False)
    assert "unignored ownership metadata" in result.stdout
    (repository / ".gitignore").write_text("/nested-vault/.vault-meta/\n")
    run(middleware / "sync.py", nested)
    page.write_text('---\ntype: note\ntitle: Updated\n---\n')
    run(middleware / "sync.py", nested)
    assert "[Updated](page.md)" in (nested / "wiki/index.md").read_text()

with tempfile.TemporaryDirectory() as temp:
    repository = Path(temp) / "repository"
    repository.mkdir()
    subprocess.run(["git", "init", "-q", str(repository)], check=True)
    (repository / ".gitignore").write_text("/.vault-meta/\n")
    (repository / "wiki").mkdir()
    (repository / "wiki/page.md").write_text('---\ntype: note\ntitle: Linked\n---\n')
    subprocess.run(["git", "-C", str(repository), "add", ".gitignore", "wiki"], check=True)
    subprocess.run(["git", "-C", str(repository), "config", "user.name", "test"], check=True)
    subprocess.run(["git", "-C", str(repository), "config", "user.email", "test@example.invalid"], check=True)
    subprocess.run(["git", "-C", str(repository), "commit", "-qm", "base"], check=True)
    linked = Path(temp) / "linked-worktree"
    subprocess.run(["git", "-C", str(repository), "worktree", "add", "-q", "-b", "linked", str(linked)], check=True)
    run(middleware / "sync.py", linked)
    linked_git_dir = Path(subprocess.check_output(["git", "-C", str(linked), "rev-parse", "--absolute-git-dir"], text=True).strip())
    assert (linked_git_dir / "okf-index-ownership.json").is_file()
    assert not (linked / ".vault-meta").exists()

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    empty = root / "wiki" / "topic"
    empty.mkdir(parents=True)
    page = empty / "page.md"
    page.write_text("---\\ntype: note\\n---\\n")
    sync = middleware / "sync.py"
    run(sync, root, "--dir", "topic")
    index = empty / "index.md"
    assert index.exists()
    page.unlink()
    run(sync, root, "--dir", "topic", "--dry-run")
    assert index.exists()
    run(sync, root, "--dir", "topic")
    assert not index.exists()

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    wiki = root / "wiki"
    nested = wiki / "nested"
    nested.mkdir(parents=True)
    page = nested / "page.md"
    page.write_text("---\ntype: note\ntitle: Before\n---\n")
    index = nested / "index.md"
    sync_module.sync_directory(wiki, "nested")
    page.write_text("---\ntype: note\ntitle: After\n---\n")
    outside = root / "outside.md"
    outside.write_text("outside sentinel\n")
    real_link = sync_module.os.link
    injected = [False]

    def swap_for_symlink(src, dst, *args, **kwargs):
        if dst == "index.md" and not injected[0]:
            injected[0] = True
            index.symlink_to(outside)
        return real_link(src, dst, *args, **kwargs)

    with patch.object(sync_module.os, "link", swap_for_symlink):
        status, _, detail = sync_module.sync_directory(wiki, "nested")
    assert injected[0], "write-time symlink injection did not execute"
    assert status == "ERROR", detail
    assert outside.read_text() == "outside sentinel\n"
    assert "recover previous index at" in detail

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    wiki = root / "wiki"
    nested = wiki / "nested"
    nested.mkdir(parents=True)
    page = nested / "page.md"
    page.write_text("---\ntype: note\ntitle: Before\n---\n")
    sync_module.sync_directory(wiki, "nested")
    index = nested / "index.md"
    original_inode = index.stat().st_ino
    page.write_text("---\ntype: note\ntitle: After\n---\n")
    real_read_index = sync_module._read_index_at
    injected = [False]

    def same_inode_edit(directory_fd, name="index.md"):
        result = real_read_index(directory_fd, name)
        if name == "index.md" and not injected[0]:
            injected[0] = True
            with open(index, "ab") as stream:
                stream.write(b"\\nconcurrent same-inode edit\\n")
        return result

    with patch.object(sync_module, "_read_index_at", same_inode_edit):
        status, _, detail = sync_module.sync_directory(wiki, "nested")
    assert injected[0], "same-inode edit injection did not run"
    assert status == "ERROR", detail
    assert index.stat().st_ino == original_inode
    assert index.read_bytes().endswith(b"\\nconcurrent same-inode edit\\n")

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    wiki = root / "wiki"
    nested = wiki / "nested"
    nested.mkdir(parents=True)
    page = nested / "page.md"
    page.write_text("---\ntype: note\n---\n")
    sync_module.sync_directory(wiki, "nested")
    page.unlink()
    index = nested / "index.md"
    user_file = nested / ".user-index.md"
    user_file.write_text("preserve me\n")
    real_rename = sync_module.os.rename

    def swap_before_quarantine(src, dst, *args, **kwargs):
        if src == "index.md":
            index.unlink()
            user_file.rename(index)
        return real_rename(src, dst, *args, **kwargs)

    with patch.object(sync_module.os, "rename", swap_before_quarantine):
        sync_module.sync_directory(wiki, "nested")
    assert index.read_text() == "preserve me\n"

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    wiki = root / "wiki"
    nested = wiki / "nested"
    nested.mkdir(parents=True)
    (nested / "page.md").write_text('---\ntype: note\ntitle: "Original"\n---\n')
    sync_module.sync_directory(wiki, "nested")
    index = nested / "index.md"
    (nested / "page.md").write_text('---\ntype: note\ntitle: "Updated"\n---\n')
    real_read = sync_module._read_index_at
    injected = [False]

    def fail_quarantine_read(directory_fd, name="index.md"):
        if name.endswith(".recovery") and not injected[0]:
            injected[0] = True
            raise PermissionError("injected quarantine read failure")
        return real_read(directory_fd, name)

    with patch.object(sync_module, "_read_index_at", fail_quarantine_read):
        status, _, detail = sync_module.sync_directory(wiki, "nested")
    assert injected[0], "quarantine read fault injection did not execute"
    assert status == "ERROR", detail
    assert index.exists() and "Original" in index.read_text()
    assert "could not verify quarantined index" in detail

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    wiki = root / "wiki"
    nested = wiki / "nested"
    nested.mkdir(parents=True)
    (nested / "page.md").write_text('---\ntype: note\ntitle: "Original"\n---\n')
    sync_module.sync_directory(wiki, "nested")
    index = nested / "index.md"
    foreign = nested / ".foreign-index.md"
    foreign.write_text("foreign arrival\n")
    real_link = sync_module.os.link
    injected = [False]

    def arrive_before_replace(src, dst, *args, **kwargs):
        if dst == "index.md" and not injected[0]:
            injected[0] = True
            foreign.rename(index)
        return real_link(src, dst, *args, **kwargs)

    (nested / "page.md").write_text('---\ntype: note\ntitle: "Changed"\n---\n')
    with patch.object(sync_module.os, "link", arrive_before_replace):
        status, _, detail = sync_module.sync_directory(wiki, "nested")
    assert injected[0], "replacement race injection did not run"
    assert status == "ERROR", detail
    assert index.read_text() == "foreign arrival\n"
    recovery_name = detail.rsplit("recover previous index at ", 1)[-1]
    recovery = nested / recovery_name
    assert recovery.exists(), "prior generated index was not retained for recovery"
    assert "Original" in recovery.read_text()

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    wiki = root / "wiki"
    nested = wiki / "nested"
    nested.mkdir(parents=True)
    (nested / "page.md").write_text('---\ntype: note\ntitle: "Pinned"\n---\n')
    build_content = sync_module.build_index_content
    injected = [False]

    def replace_public_directory(path, is_root, directory_fd=None):
        if not injected[0]:
            injected[0] = True
            nested.rename(wiki / ".nested-original")
            replacement = wiki / "nested"
            replacement.mkdir()
            (replacement / "foreign.md").write_text(
                '---\ntype: note\ntitle: "FOREIGN SECRET"\n---\n')
        content = build_content(path, is_root, directory_fd)
        assert "Pinned" in content
        assert "FOREIGN SECRET" not in content
        return content

    with patch.object(sync_module, "build_index_content", replace_public_directory):
        status, _, detail = sync_module.sync_directory(wiki, "nested")
    assert injected[0], "directory replacement injection did not run"
    assert status == "ERROR", detail
    original_index = wiki / ".nested-original" / "index.md"
    assert not original_index.exists() or "FOREIGN SECRET" not in original_index.read_text()
    replacement_index = wiki / "nested" / "index.md"
    assert not replacement_index.exists() or "FOREIGN SECRET" not in replacement_index.read_text()

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    wiki = root / "wiki"
    weird = wiki / "dir [x]"
    weird.mkdir(parents=True)
    (weird / "note [x].MD").write_text('---\ntype: note\ntitle: "Title [x]"\n---\n')
    (weird / "view [x].base").write_text("filters: {}\n")
    content = sync_module.build_index_content(wiki, True)
    assert "[dir \\[x\\]/]" in content
    nested_content = sync_module.build_index_content(weird, False)
    assert "[Title \\[x\\]](note%20%5Bx%5D.MD)" in nested_content
    assert "[view \\[x\\]](view%20%5Bx%5D.base)" in nested_content

with tempfile.TemporaryDirectory() as temp:
    root = Path(temp) / "vault"
    wiki = root / "wiki"
    wiki.mkdir(parents=True)
    filenames = ("hash#name.md", "percent%23.md", "bracket[name].md")
    for filename in filenames:
        (wiki / filename).write_text(
            f'---\ntype: note\ntitle: "Title for {filename}"\n---\n'
        )
    source = wiki / "source.md"
    source.write_text(
        "---\ntype: note\n---\n"
        "[missing](missing%20target.md)\n"
        "[missing fragment](bracket%5Bname%5D.md#not-here)\n"
    )
    run(middleware / "sync.py", root)
    report = json.loads(run(middleware / "lint.py", root).stdout)
    generated_findings = [
        entry for entry in report["dead_links"]
        if entry["source"].endswith("index.md")
    ]
    assert not generated_findings, generated_findings
    assert not report["orphans"], report["orphans"]
    assert {entry["reason"] for entry in report["dead_links"]} >= {
        "target-not-found", "heading-not-found"
    }, report["dead_links"]

print("wiki middleware boundary regressions PASS")
